### ISSUE TITLE
No such file to load puppet/util/network_device/transport_ios/ssh after module install

### ISSUE THREAD

**Issue by heathdbrown** [uniak/puppet-networkdevice#1]
After module installation, I am receiving the following error when running puppet device.

Error: Could not run: no such file to load -- puppet/util/network_device/transport_ios/ssh

**Comment by mburger** [comment]
I'm guessing that you're trying to use the ssh transport like so:

```
url ssh://$user:$pass@$switch_fqdn:$ssh_port/?$flags
```

it should be _sshios://_ not ssh:// for now to use the correct transport, this is here to avoid collusion with the functionality already provided by puppet

if i'm wrong please let me know :) and i'll take a look shortly

**Comment by heathdbrown** [comment]
You are correct, I was using ssh instead of sshios.

I changed it and it works.
